const getData = () => [
    {imgSrc: "./img/pok1.jpg", name: "pok1"},
    {imgSrc: "./img/pok2.jpg", name: "pok2"},
    {imgSrc: "./img/pok3.jpg", name: "pok3"},
    {imgSrc: "./img/pok4.png", name: "pok4"},
    {imgSrc: "./img/pok5.png", name: "pok5"},
    {imgSrc: "./img/pok6.png", name: "pok6"},
    {imgSrc: "./img/pok7.png", name: "pok7"},
    {imgSrc: "./img/pok8.jpg", name: "pok8"},
    {imgSrc: "./img/pok9.png", name: "pok9"},
    {imgSrc: "./img/pok10.png", name: "pok10"},
    {imgSrc: "./img/pok11.jpg", name: "pok11"},
    {imgSrc: "./img/pok12.jpg", name: "pok12"},
    {imgSrc: "./img/pok13.png", name: "pok13"},
    {imgSrc: "./img/pok14.jpg", name: "pok14"},
    {imgSrc: "./img/pok15.png", name: "pok15"},
    {imgSrc: "./img/pok16.png", name: "pok16"},
    {imgSrc: "./img/pok1.jpg", name: "pok1"},
    {imgSrc: "./img/pok2.jpg", name: "pok2"},
    {imgSrc: "./img/pok3.jpg", name: "pok3"},
    {imgSrc: "./img/pok4.png", name: "pok4"},
    {imgSrc: "./img/pok5.png", name: "pok5"},
    {imgSrc: "./img/pok6.png", name: "pok6"},
    {imgSrc: "./img/pok7.png", name: "pok7"},
    {imgSrc: "./img/pok8.jpg", name: "pok8"},
    {imgSrc: "./img/pok9.png", name: "pok9"},
    {imgSrc: "./img/pok10.png", name: "pok10"},
    {imgSrc: "./img/pok11.jpg", name: "pok11"},
    {imgSrc: "./img/pok12.jpg", name: "pok12"},
    {imgSrc: "./img/pok13.png", name: "pok13"},
    {imgSrc: "./img/pok14.jpg", name: "pok14"},
    {imgSrc: "./img/pok15.png", name: "pok15"},
    {imgSrc: "./img/pok16.png", name: "pok16"},
];

export default getData;